
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - get
  - patch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - patch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - get
  - patch
- apiGroups:
  - egress.monzo.com
  resources:
  - externalservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - egress.monzo.com
  resources:
  - externalservices/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking
  resources:
  - networkpolicies
  verbs:
  - create
  - get
  - patch
